!
frr version 10.0_git
frr defaults traditional
hostname r1
no ipv6 forwarding
!
interface eth1
 description To r2
 ip address 10.10.0.10/24
exit
!
interface lo
 ip address 1.1.1.1/32
exit
!
ip route 1.1.1.0/24 lo
!
route-map STATIC-TO-OSPF deny 10
exit
!
router ospf
 ospf router-id 1.1.1.1
 network 10.10.0.0/24 area 0
 redistribute static route-map STATIC-TO-OSPF
exit
!
end
