hostname r2
interface eth1
 ip address 10.10.0.20/24
exit
interface lo
 ip address 2.2.2.2/32
exit
ip route 2.2.2.0/24 lo
router ospf
 ospf router-id 2.2.2.2
 network 10.10.0.0/24 area 0
 network 2.2.2.2/32 area 0
exit
router bgp 65001
 bgp router-id 2.2.2.2
 timers bgp 3 9
 neighbor 1.1.1.1 remote-as 65001
 neighbor 1.1.1.1 update-source lo
 neighbor 1.1.1.1 passive
 address-family ipv4 unicast
  neighbor 1.1.1.1 activate
  network 2.2.2.0/24
 exit-address-family
exit
end
