!
hostname r1
!
interface eth1
 ip address 10.10.0.10/24
exit
ip prefix-list FILTER seq 5 permit 2.2.2.0/24
ip prefix-list FILTER seq 100 permit 0.0.0.0/0 le 32
route-map INBOUND permit 10
 match ip address prefix-list FILTER
exit
router bgp 65001
 bgp router-id 10.10.0.10
 timers bgp 3 9
 no bgp ebgp-requires-policy
 neighbor 10.10.0.20 remote-as 65002
 address-family ipv4 unicast
  neighbor 10.10.0.20 route-map INBOUND in
 exit-address-family
exit
!
end
