frr version 8.4_git
frr defaults traditional
hostname r2
no ipv6 forwarding
!
ip route 8.8.8.0/24 Null0
ip route 9.9.9.0/24 Null0
!
interface eth1
 ip address 10.1.12.2/24
exit
!
interface lo
 ip address 2.2.2.2/32
exit
!
router bgp 65002
 bgp router-id 2.2.2.2
 no bgp ebgp-requires-policy
 neighbor 10.1.12.1 remote-as 65001
 !
 address-family ipv4 unicast
  network 2.2.2.2/32
  network 8.8.8.0/24
  network 9.9.9.0/24
  neighbor 10.1.12.1 route-map TO_R1 out
 exit-address-family
exit
!
ip prefix-list PL_9999 seq 5 permit 9.9.9.0/24
!
route-map TO_R1 permit 10
 match ip address prefix-list PL_9999
 set as-path prepend 65002
exit
!
route-map TO_R1 permit 20
exit
!
end
