frr defaults traditional
hostname r1
service integrated-vtysh-config
!
interface lo
 ip address 1.1.1.1/32
 ip ospf area 0
!
router ospf
 ospf router-id 1.1.1.1
!
line vty
!
!
interface eth0
 ip ospf area 0
exit
!
end
