!
hostname r2
!
interface eth1
 ip address 10.10.0.20/24
exit
interface lo
 ip address 2.2.2.2/32
exit
ip route 7.7.7.0/24 lo
ip route 1.1.1.0/24 lo
ip route 2.2.2.0/24 lo
ip route 3.3.3.0/24 lo
ip route 4.4.4.0/24 lo
ip route 5.5.5.0/24 lo
ip route 6.6.6.0/24 lo
ip route 10.0.0.0/8 lo
ip route 172.16.0.0/12 lo
ip route 192.168.0.0/16 lo
router bgp 65002
 bgp router-id 2.2.2.2
 timers bgp 3 9
 no bgp ebgp-requires-policy
 neighbor 10.10.0.10 remote-as 65001
 address-family ipv4 unicast
  network 7.7.7.0/24
  network 1.1.1.0/24
  network 2.2.2.0/24
  network 3.3.3.0/24
  network 4.4.4.0/24
  network 5.5.5.0/24
  network 6.6.6.0/24
  network 10.0.0.0/8
  network 172.16.0.0/12
  network 192.168.0.0/16
 exit-address-family
exit
!
end
