frr version 8.4_git
frr defaults traditional
hostname r1
no ipv6 forwarding
!
interface eth1
 ip address 10.1.12.1/24
exit
!
interface eth2
 ip address 10.1.13.1/24
exit
!
interface lo
 ip address 1.1.1.1/32
exit
!
router bgp 65001
 bgp router-id 1.1.1.1
 no bgp ebgp-requires-policy
 neighbor 10.1.12.2 remote-as 65002
 neighbor 10.1.13.3 remote-as 65003
 !
 address-family ipv4 unicast
  network 1.1.1.1/32
  neighbor 10.1.12.2 route-map FROM_R2 in
  neighbor 10.1.13.3 route-map FROM_R3 in
 exit-address-family
exit
!
ip prefix-list PL_8888 seq 5 permit 8.8.8.0/24
!
route-map FROM_R2 permit 10
 match ip address prefix-list PL_8888
 set local-preference 50
exit
!
route-map FROM_R2 permit 20
exit
!
route-map FROM_R3 permit 10
 set local-preference 100
exit
!
end
