!
frr version 10.0_git
frr defaults traditional
hostname r1
no ipv6 forwarding
!
interface eth1
 description To r2
 ip address 10.10.0.10/24
exit
!
router bgp 65001
 bgp router-id 10.10.0.10
 no bgp ebgp-requires-policy
 timers bgp 3 9
 neighbor 10.10.0.2 remote-as 65002
 neighbor 10.10.0.2 timers connect 5
exit
!
end
