frr version 8.4_git
frr defaults traditional
hostname r1
no ipv6 forwarding
!
interface eth1
 ip address 10.10.0.10/24
exit
!
interface eth2
 ip address 10.11.0.10/24
exit
!
!
router bgp 65001
 bgp router-id 10.11.0.10
 no bgp ebgp-requires-policy
 neighbor 10.10.0.20 remote-as 65002
 neighbor 10.11.0.20 remote-as 65003
 !
 address-family ipv4 unicast
  neighbor 10.10.0.20 route-map LOW-LP in
 exit-address-family
exit
!
! r2 (via 10.10.0.20) is preferred with LocalPref 150 (>r3 default 100),
! so r1 selects r2 (fast ISP) as best by Local Preference (150 > 100) — RCL Q21 solved.
route-map LOW-LP permit 10
 set local-preference 150
exit
!
end
