frr defaults traditional
hostname r2
service integrated-vtysh-config
!
interface lo
 ip address 2.2.2.2/32
 ip ospf area 0
!
router ospf
 ospf router-id 2.2.2.2
!
line vty
!
!
interface eth0
 ip ospf area 0
exit
!
interface eth1
 ip ospf area 0
exit
!
end
