!
hostname r1
!
interface eth1
 ip address 10.10.0.10/24
exit
interface eth2
 ip address 10.11.0.10/24
 ip ospf hello-interval 5
exit
router ospf
 ospf router-id 10.11.0.10
 network 10.11.0.0/24 area 0
exit
!
ip route 3.3.3.3/32 10.10.0.20 120
end
