frr version 8.4_git
frr defaults traditional
hostname r3
no ipv6 forwarding
!
ip route 8.8.8.0/24 lo
!
!
interface lo
 ip address 8.8.8.8/32
exit
!
router bgp 65003
 bgp router-id 3.3.3.3
 no bgp ebgp-requires-policy
 neighbor 10.11.0.10 remote-as 65001
 !
 address-family ipv4 unicast
  network 8.8.8.0/24
 exit-address-family
exit
!
end
