!
frr version 10.0_git
frr defaults traditional
hostname Router
no ipv6 forwarding
!
interface eth1
 description To inet
 ip address 10.10.0.10/24
exit
!
interface eth2
 description To sv
 ip address 10.11.0.10/24
exit
ip route 0.0.0.0/0 10.10.0.1
!
end
