!
hostname r1
!
interface eth1
 ip address 10.10.0.10/24
exit
ip prefix-list NO-BOGON seq 5 deny 10.0.0.0/8 le 32
ip prefix-list NO-BOGON seq 10 permit 172.16.0.0/12 le 32
ip prefix-list NO-BOGON seq 100 permit 0.0.0.0/0 le 32
route-map INBOUND permit 10
 match ip address prefix-list NO-BOGON
exit
router bgp 65001
 bgp router-id 10.10.0.10
 timers bgp 3 9
 no bgp ebgp-requires-policy
 neighbor 10.10.0.20 remote-as 65002
 address-family ipv4 unicast
  neighbor 10.10.0.20 maximum-prefix 5
  neighbor 10.10.0.20 route-map INBOUND in
 exit-address-family
exit
!
end
