!
frr version 10.0_git
frr defaults traditional
hostname r2
no ipv6 forwarding
!
interface eth1
 description To r1
 ip address 10.10.0.20/24
exit
!
interface eth2
 description To r3
 ip address 10.11.0.10/24
exit
!
interface lo
 ip address 2.2.2.2/32
exit
!
router bgp 65001
 bgp router-id 2.2.2.2
 no bgp ebgp-requires-policy
 timers bgp 3 9
 neighbor 1.1.1.1 remote-as 65001
 neighbor 1.1.1.1 update-source lo
 neighbor 10.11.0.20 remote-as 65002
 !
 address-family ipv4 unicast
  neighbor 10.11.0.20 route-map PERMIT in
  neighbor 10.11.0.20 route-map PERMIT out
 exit-address-family
exit
!
router ospf
 ospf router-id 2.2.2.2
 network 2.2.2.2/32 area 0
 network 10.10.0.0/24 area 0
exit
!
route-map PERMIT permit 10
exit
!
end
